### ISSUE TITLE
The player sprite doesn't show up when you return to the main menu

### ISSUE THREAD

**Issue by RoperoIvan** [polarpathgames/Final-Fantasy-Mystery-World#34]
**Summary of the bug**
The player sprite doesn't show up when you return to the main menu and you click again in the new game button

**Type**
Sprites

**Steps to reproduce the behavior**
Open the game, new game, esc to show the pause menu, click on return to the main menu, click on new game and spawn again de player.

**Expected behavior**
It should show the player sprites

**Actual behavior**
It shows the text of the main menu buttons.

**Build**
0.2.0

**Date**
25/03/2019

**Additional comments**

**Comment by OriolCS2** [comment]
JAJAJAAJAJAJA cunde aixo de les issues
