### ISSUE TITLE
When you die the player appear with the death animation when revived

### ISSUE THREAD

**Issue by RoperoIvan** [polarpathgames/Final-Fantasy-Mystery-World#380]
**Summary of the bug**
When the player dies and revives, the player current animation is the death animation.

**Type**
Animation, Death.

**Steps to reproduce the behavior**
Open the game, new game, let the enemies kill you, continue button.

**Expected behavior**
It should appear with a standing animation.

**Actual behavior**
It appears laying on the ground with the death animation.

**Build**
0.7.1

**Date**
11/05/2019

**Additional comments**

**Comment by OriolCS2** [comment]
es un error si pero esta fino xd yo lo dejaba
